blank_issues_enabled: true
contact_links:
  # - name: ğŸ“š Documentation
  #   url: https://www.reka-ui.com/
  #   about: Check the documentation for usage of Radix Vue.
  - name: ğŸ—¨ï¸ Discord
    url: https://chat.unovue.com/
    about: Join the Radix Vue Discord server.
